http://localhost/oauth/authorize?redirect_uri=http%3A%2F%2Flocalhost%0A&response_type=code&client_id=1
https://campus-2022.herokuapp.com/oauth/authorize?redirect_uri=http%3A%2F%2Flocalhost%0A&response_type=code&client_id=1


### Get Token
# @prompt code
POST /oauth/token HTTP/1.1
Host: {{ host }}
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code
&client_id={{ client_id }}
&client_secret={{ client_secret }}
&code={{ code }}
&redirect_uri=http://localhost

### user
GET /api/user HTTP/1.1
Host: {{ host }}
Accept: application/json
Authorization: Bearer {{ token }}

### class_offers
GET /api/class_offers HTTP/1.1
Host: {{ host }}
Accept: application/json
Authorization: Bearer {{ token }}
